version: '3'
services:
  mongo:
    image: 'mongo:4.2'
    restart: always
    volumes:
    - './data:/data/db'
    mem_limit: 200m
    command: ['--wiredTigerCacheSizeGB', '0.1']
  server:
    ports:
      - '18023:8000'
    image: python:3.9-slim
    volumes:
      - '.:/app'
    restart: unless-stopped
    working_dir: '/app'
    env_file: [octo.env]
    depends_on:
      - 'mongo'
    command: [ ./scripts/task.sh, server ]
  update_subs:
    image: python:3.9-slim
    volumes:
      - '.:/app'
    working_dir: '/app'
    restart: unless-stopped
    env_file: [octo.env]
    depends_on:
      - 'mongo'
    command: [ ./scripts/task.sh, cron, update_subs]
  update_index:
    image: python:3.9-slim
    volumes:
      - '.:/app'
    working_dir: '/app'
    restart: unless-stopped
    env_file: [octo.env]
    depends_on:
      - 'mongo'
    command: [ ./scripts/task.sh, cron, update_index ]
  download_images:
    image: python:3.9-slim
    volumes:
      - '.:/app'
    working_dir: '/app'
    restart: unless-stopped
    env_file: [octo.env]
    depends_on:
      - 'mongo'
    command: [ ./scripts/task.sh, cron, download_images ]
  post_images:
    image: python:3.9-slim
    volumes:
      - '.:/app'
      - '${EXTERNAL_ROOT:-./external}:/external'
    working_dir: '/app'
    restart: unless-stopped
    env_file: [octo.env]
    depends_on:
      - 'mongo'
    command: [ ./scripts/task.sh, cron, post_images ]
  clean_cache:
    image: python:3.9-slim
    volumes:
      - '.:/app'
    working_dir: '/app'
    restart: unless-stopped
    env_file: [octo.env]
    depends_on:
      - 'mongo'
    command: [ ./scripts/task.sh, cron, clean_cache ]
