version: '3'
services:
  mongo:
    image: 'mongo:4.2'
    restart: always
    volumes:
    - './data:/data/db'
  init: &py
    image: python:3.9-slim
    volumes:
      - '.:/app'
    working_dir: '/app'
    depends_on:
      - 'mongo'
    command: [ ./scripts/deps.sh ]
  server: *py
    ports:
      '18023:8000'
    command: [ ./scripts/task.sh, server ]
  cron: *py
    command: [ ./scripts/task.sh, cron ]
