version: '3'
services:
  mongo:
    image: 'mongo:4.2'
    restart: always
    volumes:
    - './data:/data/db'
    mem_limit: 120m
  init:
    image: python:3.9-slim
    volumes:
      - '.:/app'
    working_dir: '/app'
    command: [ ./scripts/deps.sh ]
  server:
    ports:
      - '18023:8000'
    image: python:3.9-slim
    volumes:
      - '.:/app'
    working_dir: '/app'
    depends_on:
      - 'mongo'
    command: [ ./scripts/task.sh, server ]
  cron:
    image: python:3.9-slim
    volumes:
      - '.:/app'
    working_dir: '/app'
    depends_on:
      - 'mongo'
    command: [ ./scripts/task.sh, cron ]
